# Generated by Django 2.2.5 on 2019-09-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuKitchenHot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_hot', models.SlugField(auto_created=True, unique=True)),
                ('title_hot', models.CharField(db_index=True, max_length=50, verbose_name='Название')),
                ('text_hot', models.TextField(verbose_name='Описание')),
                ('weight_hot', models.TextField(max_length=10, verbose_name='Вес')),
                ('price_hot', models.IntegerField(verbose_name='Цена')),
                ('image_hot', models.ImageField(upload_to='hot', verbose_name='Картинка')),
                ('date_hot_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Горячее',
                'verbose_name_plural': 'Горячее',
            },
        ),
    ]
